# SPDX-FileCopyrightText: 2023 Samuel Wu
#
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
    - package-ecosystem: npm
      target-branch: dev
      directory: /
      schedule:
          interval: monthly

    - package-ecosystem: github-actions
      target-branch: dev
      directory: /
      schedule:
          interval: monthly
