# SPDX-FileCopyrightText: 2023 Samuel Wu
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.43.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - eslint
          - eslint-config-prettier
          - eslint-config-standard-with-typescript
          - eslint-plugin-import
          - eslint-plugin-n
          - eslint-plugin-promise
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - eslint-plugin-react-refresh
          - react
          - '@react-hook/media-query'

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          - postcss
          - stylelint
          - stylelint-config-recess-order
          - stylelint-config-standard
          - stylelint-css-modules
          - stylelint-use-nesting

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
